### ISSUE TITLE
[Feature request] Configuratuion options

### ISSUE THREAD

**Issue by TitaniumHocker** [python-lsp/python-lsp-black#15]
Hello

First of all, thanks for maintaining this project!

It would be convenient if it would be possible to customize how formatting works(max line length, etc.) through the configuration of the language server or a wider list of configuration files(setup.cfg, tox.ini for example).

**Comment by haplo** [comment]
Hello @TitaniumHocker, sorry for taking this long to reply.

As mentioned in the [README](https://github.com/python-lsp/python-lsp-black/blob/master/README.md#usage):

> python-lsp-black will use your project's pyproject.toml if it has one.

*pyproject.toml* is [how black reads its configuration](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file), other configuration files are not supported. I don't think *python-lsp-black* should support any configuration files not supported by *black* itself.

About allowing black configuration through the LSP plugin configuration, I don't think it's a good idea, as other users could use *black* without LSP, and then they would use different formatting settings. Centralizing configuration into *pyproject.toml* avoids these issues.
