### ISSUE TITLE
Formatting fails silently

### ISSUE THREAD

**Issue by sblask** [python-lsp/python-lsp-black#20]
I just ran into this: https://github.com/psf/black/issues/1948 but it took me a long time to figure this out because when running formatting through the lsp-server I did not get any error at all. It's just silent  and I didn't know whether I did something wrong or not. There is nothing in the logs either. It would be good to have some kind of indication that something failed...

The error I get when running black on the command line is:

```
error: cannot format test.py: Cannot parse: 33:32:     with (fs.open(source, "rb") as source_input, fs.open( destination, "wb") as output):
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Comment by haplo** [comment]
@sblask I was able to reproduce the problem and have a solution with #22. It works for me, I now see the error in lsp stderr.
