### ISSUE TITLE
Incorrect call order when used with isort

### ISSUE THREAD

**Issue by Rahix** [python-lsp/python-lsp-black#21]
I have a python file which I want to format.  I have both [`pyls-isort`](https://github.com/paradoxxxzero/pyls-isort) and `python-lsp-black` installed.  The file contains the following lines:

```python
from typing import (
    Any,
    Callable,
    ContextManager,
    DefaultDict,
    Dict,
    Generic,
    Iterator,
    List,
    Optional,
    Set,
    Type,
    TypeVar,
    Union,
)
```

after formatting, I end up with

```python
from typing import (Any, Callable, ContextManager, DefaultDict, Dict, Generic,
                    Iterator, List, Optional, Set, Type, TypeVar, Union)
```

which is of course not the valid format from `black`.  I think what is going on here is that `isort` runs _after_ `black` and thus papers over `black`'s style.  Any idea how and where to fix this?

**Comment by haplo** [comment]
You should configure `isort` with the `black` profile, that way it won't matter which runs first. That is what I do and it works well.

Official documentation: https://pycqa.github.io/isort/docs/configuration/black_compatibility.html

**Comment by Rahix** [comment]
Interesting, thanks for the hint!
