### ISSUE TITLE
Option to cache black configuration per-file

### ISSUE THREAD

**Issue by haplo** [python-lsp/python-lsp-black#24]
Currently `load_config` is called every time the plugin is asked to format the whole document, which requires finding the root of the project the Python file to be formatted, then finding the *pyproject.toml* file if any and parsing it into a dictionary. A simple way to cache these results is by using [`lru_cache`](https://docs.python.org/3/library/functools.html#functools.lru_cache) decorator on `load_config`, however this can confuse users as changes to their *pyproject.toml* files would not be visible to *python-lsp-black* until the LSP server is restarted. For this reason config caching should be disabled by default and only enabled via explicit configuration.

Introduce a way to configure the behavior of *python-lsp-black*, starting with a `cache_config` setting that defaults to `None`. When set to an integer value it will be used for the `lru_cache` call on `load_config`.

**Comment by haplo** [comment]
I have put this change in the `cache-config` branch if anybody is interested in trying it out. It's not yet configurable, meaning config caching will be always enabled in this branch until I have time to implement plugin configuration.

**Comment by ccordoba12** [comment]
Could you create a PR out of that branch? I'd like to take a look at it.

**Comment by haplo** [comment]
@ccordoba12 Please see #26. Let me know if you plan on working on it so we don't overlap.
