### ISSUE TITLE
python-lsp-black does not respect black configurations

### ISSUE THREAD

**Issue by mattishallen** [python-lsp/python-lsp-black#35]
Hi! I use this plugin with neovim's built in LSP and call it from `vim.lsp.buf.formatting`. The formatting works but it does not respect my black configurations, neither my global config in `~/.config/black` nor `pyproject.toml` in project roots. I also have black installed from pip and there everything works fine.

`pyproject.toml`:

```
[tool.black]
line-length = 80
experimental-string-processing = true
target-version = ["py38"]
skip-string-normalization = true
```
pylsp-black config in `init.lua`:
```
    settings = {
      pylsp = {
        plugins = {
          black = {
            enabled = true,
            cache_config = false,
            line_length = 80,
          },

```

However when I format this code

![image](https://user-images.githubusercontent.com/9672054/175503173-a47687c0-1b94-4ca5-9071-af49b1f10654.png)
 
the underlined error (line length 83 > 80) is not formatted. If i format this using `black` directly in a shell it is formatted.

**Comment by JesusTorrado** [comment]
Hi both,

In case it helps, I am finding a similar issue to @mattishallen's in `emacs`+`eglot`. In particular, it is just the `preview` option that is not applied (in particular the string reflow), while the line length is respected.

My running `pylsp` configuration is

    "pylsp": {
        "plugins": {
          "black": {
            "enabled": true,
            "line_length": 90,  # acknowledged
            "preview": true,  # ignored
            "cache_config": null
          }

A `black --preview` shell call works as expected.

My `black` version is `22.10.0` and my `python-lsp-black` version is `1.2.1`.

`eglot` does not provide access to the LSP logs AFAIK, so not sure whether I can help much with this.

**Comment by JesusTorrado** [comment]
Maybe setting a `preview` kwarg is missing in this definition? https://github.com/python-lsp/python-lsp-black/blob/c3c0c1d4c368e67bcc6eaff5c356a233e53c9c3f/pylsp_black/plugin.py#L85

**Comment by haplo** [comment]
@JesusTorrado Would you mind creating a PR with the fix at https://github.com/JesusTorrado/python-lsp-black/commit/4b8000753c09e55a5c385175e542e686c520a21d?

**Comment by JesusTorrado** [comment]
Hi @haplo 
Not sure I understand what you are asking me to do: there is already a PR at https://github.com/python-lsp/python-lsp-black/pull/38

**Comment by mahmoudajawad** [comment]
@haplo any update on this? Can #38 be merged and a new release be made so we benefit from black preview features?

**Comment by haplo** [comment]
I apologize for the long delay, I have merged the changes and I'm working towards making a new release with this and other changes.

**Comment by mahmoudajawad** [comment]
@haplo, no apology needed. Everything you do is much appreciated and I thank you for making it possible for us to use black with lsp.

Keep up the good work!

**Comment by haplo** [comment]
> @haplo, no apology needed. Everything you do is much appreciated and I thank you for making it possible for us to use black with lsp.
> 
> Keep up the good work!

Thank you for the kind words. :heart:  The reality is that I used to work daily with Python, so I was an active user. Now I use Python more sporadically for some personal projects, so finding time for maintenance is harder.

In other news: [python-lsp-black 1.3.0 is out]()! :tada:
