### ISSUE TITLE
Further maintanance and administration

### ISSUE THREAD

**Issue by andfoy** [python-lsp/python-lsp-black#4]
Since this is a community-based repository and most of the members of the Spyder IDE team do not have much time to maintain the external plugins for the python-lsp-server, we are going to delegate this repository to any person that is interested on doing so. By accepting to be a maintainer of the repository, you will be on charge of attending the issue tracker, setting the release milestones, reviewing and merging PRs as well as doing releases to PyPi.

The process of maintaining the repo will be described on a MANTAINANCE.md document that is going to live on the root of this repository. In order to be registered as a maintainer, we'll require your PyPi and GitHub usernames.

cc @haplo @s7726

**Comment by haplo** [comment]
You can count on me as a maintainer. My PyPI user is `fidelramos`.

**Comment by andfoy** [comment]
@haplo, I've just invited you to be maintainer both in the repo and PyPi, please let me know if you understand the instructions declared in https://github.com/python-lsp/python-lsp-black/blob/master/MAINTENANCE.md and https://github.com/python-lsp/python-lsp-black/blob/master/RELEASE.md

**Comment by haplo** [comment]
Thank you @andfoy.

About the release procedure, maybe we could add a Github action that automates the process, similar to what [mypy-ls does](https://github.com/Richardk2n/mypy-ls/blob/master/.github/workflows/python-publish.yml). If you agree I will open an issue and work on it.

**Comment by andfoy** [comment]
Sure, feel free to take the actions that you see necessary here

**Comment by haplo** [comment]
I released v1.0.1 following [the release instructions](https://github.com/python-lsp/python-lsp-black/blob/374969126a3cac619f547d4415522c7ee470a669/RELEASE.md) and everything went well. Thank you for the documentation @andfoy. :raised_hands:
