### ISSUE TITLE
Ineffective range formatting

### ISSUE THREAD

**Issue by ramnes** [python-lsp/python-lsp-black#42]
Hey there, thanks for the great plugin!

It seems that range formatting isn't really effective with python-lsp-black. If you try to format a few lines inside a function, nothing will change:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/835072/221250833-65067c81-270d-4b69-a71b-323e5d5e92fa.png">

It does work great if you format the whole function, though:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/835072/221250622-b7ead5e7-59df-4498-8555-1ce76a946dea.png">

Also, it will trim whitespaces if you select those (notice the line returns that disappeared between the two functions):
<img width="577" alt="image" src="https://user-images.githubusercontent.com/835072/221251114-cb39e4d9-b763-4103-b28a-200dcfeb04ad.png">
 

I previously used a (non-LSP) package based on [black-machiatto](https://github.com/wbolster/black-macchiato) that gave excellent results for that kind of operations.

Would you consider using black-machiatto in python-lsp-black as well for range formatting?

**Comment by ramnes** [comment]
Apparently there's also [pyink](https://github.com/google/pyink), a fork of black made by Google, that supports range formatting.

**Comment by haplo** [comment]
Hi @ramnes.

The limited usefulness of region formatting is a known limitation, it's mentioned in the README:

> Text selections are treated as if they were a separate Python file. Unfortunately this means you can't format an indented block of code.

I wouldn't oppose a PR that adds support for black-machiatto, but it should be optional, tested and documented.

**Comment by remisalmon** [comment]
Black supports range formatting as of https://github.com/psf/black/releases/tag/23.11.0 I have open a pull request that may fix this at https://github.com/python-lsp/python-lsp-black/pull/52.
