### ISSUE TITLE
Use with ruff plugin

### ISSUE THREAD

**Issue by linsui** [python-lsp/python-lsp-black#43]
When I add  `black = {}`, this plugin doesn't work and ruff can't format the code, either. When I add `black = { enable = true }` both of them work. I thought it's enabled by default. Why doesn't it work and make ruff stop working? Thanks!

**Comment by ccordoba12** [comment]
Hey @linsui, thanks for reporting. To disable the Black plugin you need to use `pylsp_black = {enable = false`. See issue #41 for details.

**Comment by linsui** [comment]
Ah, I thought I found a weird behavior. It seems as long as the black setting is not empty, e.g.

```lua
 black = {
  a = true,
},
```

this plugin is enabled. But if it's empty somehow the ruff plugin doesn't work either.

**Comment by ccordoba12** [comment]
Ok, but what happens if you follow my suggestion?

**Comment by linsui** [comment]
`pylsp_black = {enable = true}` works well. :ok:

**Comment by ccordoba12** [comment]
Ok, good. Then I'm going to close this issue then.
