### ISSUE TITLE
Release version 2.0

### ISSUE THREAD

**Issue by ccordoba12** [python-lsp/python-lsp-black#54]
- This is a quick issue to let everyone know that I think everything is ready for the next version of this plugin, so I'm going to proceed to release it.
- I tested our master branch in Spyder (see https://github.com/spyder-ide/spyder/pull/21629) and all its client-side tests are passing, which gives me more confidence about this.

**Comment by ccordoba12** [comment]
The release is now on PyPI: https://pypi.org/project/python-lsp-black/2.0.0/

**Comment by haplo** [comment]
Thank you for taking care of this release @ccordoba12! I apologize for my unavailability, I have been busy with personal stuff with the looming holiday season.

**Comment by ccordoba12** [comment]
No worries @haplo. I imagined that was the case: these are not the best days to release a new version. But we wanted to include the ability to format indented code in the next Spyder version, which is almost ready.

**Comment by haplo** [comment]
I didn't mean it like that, it's a great time for a release, a holiday gift! :christmas_tree:

**Comment by ccordoba12** [comment]
I didn't see it like that but you're totally right 👍🏽
