### ISSUE TITLE
Fix test failures with black 21.4b0+

### ISSUE THREAD

**Issue by ccordoba12** [python-lsp/python-lsp-black#6]
See https://github.com/rupert/pyls-black/pull/39 for the details.

**Comment by haplo** [comment]
Thank you for the heads up @ccordoba12, I will bring those fixes in and make a new release.

**Comment by haplo** [comment]
Turns out https://github.com/rupert/pyls-black/pull/39 doesn't affect python-lsp-black, tests pass in last black version.

**Comment by ccordoba12** [comment]
Glad to know :+1:
